[project]
name = "lis-optimization"
version = "0.1.0"
description = "Longest Increasing Subsequence Optimization"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.17.2",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pyzmq>=27.1.0",
]
